language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install inkscape
  - sudo apt-get install npm
  - npm config set strict-ssl false
  - sudo npm install -g less

script:
  - cargo check
  - cargo test
  - cargo test --release
