[package]
name = "rs_schafkopf"
version = "0.1.0"
authors = ["philipp"]

[dependencies]
combine = "1.3"
quickcheck = "0.2"
rand = "0.3"
ncurses = "5.82.0"
itertools = "0.4"
permutohedron = "0.2.1"
clap = "2"
arrayvec = "0.3.16"
