[package]
name = "rs_schafkopf"
version = "0.1.0"
authors = ["philipp"]

[dependencies]
combine = "1"
quickcheck = "0"
rand = "0"
ncurses = "5"
itertools = "0"
permutohedron = "0"
clap = "2"
arrayvec = "0"
crossbeam = "0"
toml = "0"
error-chain = "0"
as_num = { git = "https://github.com/phimuemue/rs_as_num" }
derive-new = "0"
