[package]
name = "rs_schafkopf"
version = "0.1.0"
authors = ["philipp"]

[dependencies]
combine = "1"
quickcheck = "0"
rand = "0"
ncurses = "5"
itertools = "0.5"
permutohedron = "0"
clap = "2"
arrayvec = "0"
