[package]
name = "openschafkopf"
version = "0.1.0"
authors = ["openschakfopf"]

[dependencies]
combine = "1"
rand = "0"
ncurses = "5"
itertools = "0"
plain_enum = "0"
permutohedron = "0"
clap = "2"
arrayvec = "0"
crossbeam = "0"
toml = "0"
as_num = "0"
error-chain = "0"
derive-new = "0"

[profile.release]
lto = true
