[package]
name = "openschafkopf_util"
version = "0.1.0"
authors = ["openschafkopf <openschafkopf>"]
edition = "2018"

[dependencies]
itertools = "0"
as_num = "0"
plain_enum = "0"
combine = "3"
derive-new = "0"
failure = { version = "0", default-features = false, features = ["std"] }
